### PR TITLE
Fix boolean blindness by introducing Boundary type

### LINKED ISSUE #4: Self-explaining type for interval boundaries
I noticed that I repeatedly forget the meaning of `Bool` in `(Extended r, Bool)`: does it stand for an open interval or for a closed one? Surely, one can always refer to haddocks, but maybe it is worth to make this parameter self-explaining? Like 

```haskell
data Strictness = Strict | NonStrict
```

or 

```haskell
data Boundary = Open | Closed 
```

### PR DESCRIPTION
**Pull request by Bodigrim**
Closes #4.

### CODE REVIEW

**Review by msakai — APPROVED** [review]
The changes looks good to me.

I'd like to change `IntegerInterval` as well, but I think either of doing so in this PR or in a separate PR is okay.

Also, because it is a breaking change, we need to bump the version number to `1.4` or `2.0`.
I prefer `2.0` in this case. What do you think?

**Comment by Bodigrim** [comment]
I do not mind `2.0`, sounds reasonable.

**Comment by Bodigrim** [comment]
Now covering `IntegerInterval` as well.

**Comment by msakai** [comment]
Thanks!
Please merge the PR.

**Pull request merged**
