### PR TITLE
fix `Data.IntegerInterval.width`

### PR DESCRIPTION
**Pull request by ncfavier**

### CODE REVIEW

**Comment by Bodigrim** [comment]
Thanks! Could you possibly add a test and rebase please?

**Comment by Bodigrim** [comment]
Thanks!

**Comment by toonn** [comment]
Should versions v1.3.1 through v2.1.1 be marked as deprecated on Hackage since they are affected by this issue? I remember getting bit by this bug last year during Advent of Code.

**Comment by Bodigrim** [comment]
If we deprecate all packages with bugs, we'll end up deprecating pretty much everything ;) IMHO old releases will fall out of use on their own.

**Pull request merged**
